excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 
  ignores_comments: true

type_name:
  excluded: ".*Test\\.swift" # regex that defines paths to exclude during linting. optional
